CREATE TABLE STUDENT (
  id         SERIAL  NOT NULL,
  first_name VARCHAR NOT NULL,
  last_name  VARCHAR NOT NULL,
  CONSTRAINT student_pk PRIMARY KEY (id)
) WITH (
OIDS = FALSE
);


CREATE TABLE TOPIC (
  id   SERIAL  NOT NULL,
  name VARCHAR NOT NULL,
  CONSTRAINT topic_pk PRIMARY KEY (id)
) WITH (
OIDS = FALSE
);


CREATE TABLE ASSESSMENT (
  id   SERIAL  NOT NULL,
  name VARCHAR NOT NULL,
  CONSTRAINT assessment_pk PRIMARY KEY (id)
) WITH (
OIDS = FALSE
);


CREATE TABLE SUMMARY_TABLE (
  id            SERIAL  NOT NULL,
  student_id    BIGINT  NOT NULL,
  topic_id      BIGINT  NOT NULL,
  assessment_id BIGINT  NOT NULL,
  value         VARCHAR NOT NULL,
  CONSTRAINT summary_table_pk PRIMARY KEY (id)
) WITH (
OIDS = FALSE
);


ALTER TABLE SUMMARY_TABLE
  ADD CONSTRAINT summary_table_fk0 FOREIGN KEY (student_id) REFERENCES STUDENT (id);
ALTER TABLE SUMMARY_TABLE
  ADD CONSTRAINT summary_table_fk1 FOREIGN KEY (topic_id) REFERENCES TOPIC (id);
ALTER TABLE SUMMARY_TABLE
  ADD CONSTRAINT summary_table_fk2 FOREIGN KEY (assessment_id) REFERENCES ASSESSMENT (id);

